import { Person } from "src/utils/TS/interface";

export const team: Person[] = [
    {
        id: '1',
        photo: { url: '/people/p_1.jpg', alt: 'mitarbeiter' },
        name: 'Stefan',
        surname: 'Creus',
        title1: 'Dipl. Architekt Eth | Emba Hsg',
        title2: '',
        job1: 'Partner',
        job2: 'Geschäftsleitung',
        displayOrder: 0,
        email: 'info@dima-partner.ch',
        jobLocation: 'Glarus',
        jobCategory: 'Bauleitern',
    },
    {
        id: '2',
        photo: { url: '/people/p_2.jpg', alt: 'mitarbeiter' },
        name: 'Vito',
        surname: 'Pantelana',
        title1: 'Dipl. Architekt Eth | Sia',
        title2: '',
        job1: 'Partner | Geschäftsleitung',
        job2: 'Leiter Plannung',
        displayOrder: 1,
        email: 'info@dima-partner.ch',
        jobLocation: 'Glarus',
        jobCategory: 'Bauleitern',
    },
    {
        id: '3',
        photo: { url: '/people/p_3.jpg', alt: 'mitarbeiter' },
        name: 'Frantz',
        surname: 'Noser',
        title1: 'Architekt',
        title2: '',
        job1: 'Partner',
        job2: '',
        displayOrder: 2,
        email: 'info@dima-partner.ch',
        jobLocation: 'Glarus',
        jobCategory: 'Bauleitern',
    },
    {
        id: '4',
        photo: { url: '/people/p_4.jpg', alt: 'mitarbeiter' },
        name: 'Hansruedi',
        surname: 'Dürst',
        title1: '',
        title2: '',
        job1: 'Projektleiter',
        job2: 'Baumenagement',
        displayOrder: 2,
        email: 'info@dima-partner.ch',
        jobLocation: 'Glarus',
        jobCategory: 'Bauleitern',
    },
    {
        id: '5',
        photo: { url: '/people/p_5.jpg', alt: 'mitarbeiter' },
        name: 'Karin',
        surname: 'Fischli',
        title1: 'Eidg. Dipl. Immobilienvermarketerin',
        title2: '',
        job1: 'Käuferberatung',
        job2: '',
        displayOrder: 2,
        email: 'info@dima-partner.ch',
        jobLocation: 'Glarus',
        jobCategory: 'Bauleitern',
    },
    {
        id: '6',
        photo: { url: '/people/p_6.jpg', alt: 'mitarbeiter' },
        name: 'Jürg',
        surname: 'Fischli',
        title1: '',
        title2: '',
        job1: 'Bauleiter',
        job2: '',
        displayOrder: 2,
        email: 'info@dima-partner.ch',
        jobLocation: 'Glarus',
        jobCategory: 'Bauleitern',
    },
    {
        id: '7',
        photo: { url: '/people/p_7.jpg', alt: 'mitarbeiter' },
        name: 'Melanie',
        surname: 'Lutschiger',
        title1: 'Dipl. Technikerin Hf Hochbau',
        title2: 'Eidg. Dipl. Bauleiterin Hfp',
        job1: 'Bauleiterin',
        job2: '',
        displayOrder: 2,
        email: 'info@dima-partner.ch',
        jobLocation: 'Glarus',
        jobCategory: 'Bauleitern',
    },
]